### ISSUE TITLE
Octagon.c doesn't draw anything

### ISSUE THREAD

**Issue by matthewBeck6765** [McDermott-Group/Simulation-and-Design#1]
The title is self explanatory. Irregardless of what layer one chooses to have the octagon drawn on, nothing appears in the editor window.

**Comment by iamed18** [comment]
lol. I guess @gribeill wasn't as much of a hotshot as we all thought

**Comment by iamed18** [comment]
I'll make @bgchristensen fix it.

**Comment by matthewBeck6765** [comment]
I am almost done fixing it.

**Comment by matthewBeck6765** [comment]
Issue has been resolved. I pushed the changes accidentally under Chris' handle as he was logged in.

**Comment by gribeill** [comment]
:poop:
